version: 1.0.0
api_url: https://api.dev.5gla.de/api/v1
api_version_endpoint: /info/version
api_image_endpoint: /mica-sense/images/
api_end_transaction_endpoint: /mica-sense/images/@transaction_id/end
max_retries: 3
retry_delay_seconds: 5