version: 1.0.0
api_version_endpoint: /sec/api-key/info/version
api_image_endpoint: /sec/tenant/image-processing/images/
api_begin_transaction_endpoint: /sec/tenant/image-processing/images/@drone_id/@transaction_id/begin
api_end_transaction_endpoint: /sec/tenant/image-processing/images/@drone_id/@transaction_id/end
api_device_position_endpoint: /sec/tenant/device-position/@drone_id/@transaction_id/add
max_retries: 3
enable_image_sending: false
retry_delay_seconds: 5
trigger_photo_url: http://192.168.0.108/capture?preview=true
photo_download_url: http://192.168.0.108/files
camera_position_url: http://192.168.0.108/gps
photo_folder: /micasense_integration/pictures/
sending_interval_in_seconds: 3
drone_id: a58de346188f1236 # Maximum 16 characters
log_level: INFO
log_level.console: INFO